VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IMach4Emu"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public Sub LoadGCodeFile(ByVal Filename As String)
End Sub
Public Sub CloseFile()
End Sub
Public Function GetScriptDispatch() As Object
End Function
Public Sub ShutDown()
End Sub
Public Sub GetAxisPosition(ByRef Xpos As Double, ByRef Ypos As Double, ByRef Zpos As Double, ByRef Apos As Double, ByRef Bpos As Double, ByRef Cpos As Double)
End Sub
Public Sub CycleStart()
End Sub
Public Sub FeedHold()
End Sub
Public Sub RewindGcode()
End Sub
Public Sub GetLineNumber()
End Sub
Public Sub SetFRO(ByVal FeedOverride As Double)
End Sub
Public Function GetRev() As String
End Function


