Attribute VB_Name = "Mach3"
Option Explicit




Public g_MainFolder As String
Public g_XMLProfile As String
Public g_CurrentScreenSet As String

Public g_bLoadProfile As Boolean

Public g_asDefinitions(85) As String

Public Sub InitDefinitions()
    g_asDefinitions(0) = "Const OUTPUT1 = 7"  ' Mach3 basic definitions
    g_asDefinitions(1) = "Const OUTPUT2 = 8"
    g_asDefinitions(2) = "Const OUTPUT3 = 9"
    g_asDefinitions(3) = "Const OUTPUT4 = 10"
    g_asDefinitions(4) = "Const OUTPUT5 = 11"
    g_asDefinitions(5) = "Const OUTPUT6 = 12"
    g_asDefinitions(6) = "Const OUTPUT7 = 16"
    g_asDefinitions(7) = "Const OUTPUT8 = 17"
    g_asDefinitions(8) = "Const OUTPUT9 = 18"
    g_asDefinitions(9) = "Const OUTPUT10 = 19"
    g_asDefinitions(10) = "Const OUTPUT11 = 20"
    g_asDefinitions(11) = "Const OUTPUT12 = 21"
    g_asDefinitions(12) = "Const OUTPUT13 = 22"
    g_asDefinitions(13) = "Const OUTPUT14 = 23"
    g_asDefinitions(14) = "Const OUTPUT15 = 24"
    g_asDefinitions(15) = "Const OUTPUT16 = 25"
    g_asDefinitions(16) = "Const OUTPUT17 = 26"
    g_asDefinitions(17) = "Const OUTPUT18 = 27"
    g_asDefinitions(18) = "Const OUTPUT19 = 28"
    g_asDefinitions(19) = "Const OUTPUT20 = 29"
    g_asDefinitions(20) = "Const DIGTRIGGER = 0"
    g_asDefinitions(21) = "Const ENABLE1 = 1"
    g_asDefinitions(22) = "Const ENABLE2 = 2"
    g_asDefinitions(23) = "Const ENABLE3 = 3"
    g_asDefinitions(24) = "Const ENABLE4 = 4"
    g_asDefinitions(25) = "Const ENABLE5 = 5"
    g_asDefinitions(26) = "Const ENABLE6 = 6"
    g_asDefinitions(27) = "Const CHARGE  =  13"
    g_asDefinitions(28) = "Const CHARGE2 =  14"
    g_asDefinitions(29) = "Const CURRENTHILOW = 15"
    g_asDefinitions(30) = "Const XPLUS  = 0"
    g_asDefinitions(31) = "Const XMINUS = 1"
    g_asDefinitions(32) = "Const XHOME  =  2"
    g_asDefinitions(33) = "Const YPLUS =  3"
    g_asDefinitions(34) = "Const YMINUS =  4"
    g_asDefinitions(35) = "Const YHOME =  5"
    g_asDefinitions(36) = "Const ZPLUS =  6"
    g_asDefinitions(37) = "Const ZMINUS =  7"
    g_asDefinitions(38) = "Const ZHOME =  8"
    g_asDefinitions(39) = "Const APLUS =  9"
    g_asDefinitions(40) = "Const AMINUS =  10"
    g_asDefinitions(41) = "Const AHOME  =  11"
    g_asDefinitions(42) = "Const BPLUS  = 12"
    g_asDefinitions(43) = "Const BMINUS = 13"
    g_asDefinitions(44) = "Const BHOME  = 14"
    g_asDefinitions(45) = "Const CPLUS  = 15"
    g_asDefinitions(46) = "Const CMINUS = 16"
    g_asDefinitions(47) = "Const CHOME  = 17"
    g_asDefinitions(48) = "Const INPUT1 = 18"
    g_asDefinitions(49) = "Const INPUT2 = 19"
    g_asDefinitions(50) = "Const INPUT3 = 20"
    g_asDefinitions(51) = "Const INPUT4 = 21"
    g_asDefinitions(52) = "Const DIGITIZE  = 22"
    g_asDefinitions(53) = "Const INDEX   = 23"
    g_asDefinitions(54) = "Const LIMITOVER  = 24"
    g_asDefinitions(55) = "Const EMERGENCY   =  25"
    g_asDefinitions(56) = "Const THCON   = 26"
    g_asDefinitions(57) = "Const THCUP   = 27"
    g_asDefinitions(58) = "Const THCDOWN = 28"
    g_asDefinitions(59) = "Const OEMTRIG1 = 29"
    g_asDefinitions(60) = "Const OEMTRIG2 = 30"
    g_asDefinitions(61) = "Const OEMTRIG3 = 31"
    g_asDefinitions(62) = "Const OEMTRIG4  = 32"
    g_asDefinitions(63) = "Const OEMTRIG5  = 33"
    g_asDefinitions(64) = "Const OEMTRIG6  = 34"
    g_asDefinitions(65) = "Const OEMTRIG7  = 35"
    g_asDefinitions(66) = "Const OEMTRIG8  = 36"
    g_asDefinitions(67) = "Const OEMTRIG9  = 37"
    g_asDefinitions(68) = "Const OEMTRIG10 = 38"
    g_asDefinitions(69) = "Const OEMTRIG11 = 39"
    g_asDefinitions(70) = "Const OEMTRIG12 = 40"
    g_asDefinitions(71) = "Const OEMTRIG13 = 41"
    g_asDefinitions(72) = "Const OEMTRIG14 = 42"
    g_asDefinitions(73) = "Const OEMTRIG15 = 43"
    g_asDefinitions(74) = "Const TIMING   = 44"
    g_asDefinitions(75) = "Const JOGXP    = 45"
    g_asDefinitions(76) = "Const JOGXM    = 46"
    g_asDefinitions(77) = "Const JOGYP    = 47"
    g_asDefinitions(78) = "Const JOGYM    = 48"
    g_asDefinitions(79) = "Const JOGZP    = 49"
    g_asDefinitions(80) = "Const JOGZM    = 50"
    g_asDefinitions(81) = "Const JOGAP    = 51"
    g_asDefinitions(82) = "Const JOGAM    = 52"
    g_asDefinitions(83) = "Const HOMING   = 53"
    g_asDefinitions(84) = "Const PROBING  = 54"
    g_asDefinitions(85) = "Const START    = 55"
End Sub

